#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r "*"

~/.config/bspwm/autostart.sh &

bspc config window_gap 10

bspc config top_padding 58
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10

bspc config border_width         3
bspc config focused_border_color "#FFFFFF"

bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_motion_interval 7ms
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config ignore_ewmh_focus true

bspc rule -a discord desktop="^4" follow=off focus=off
